[package]
name = "ascii-img"
version = "0.1.0"
edition = "2024"
description = "ASCII art library"
license = "MPL-2.0"
authors = ["4yman-0"]

[dependencies]
image = { version = "0.25.5", default-features = false }
