[package]
name = "ascii-img"
version = "0.1.0"
edition = "2024"
description = "ASCII art library"
license = "MPL-2.0"
authors = ["4yman-0"]

[features]
default = ["ascii-renderer", "ansi-renderer", "unicode-renderer"]
ascii-renderer = []
ansi-renderer = ["dep:ansi_term"]
unicode-renderer = []

[dependencies]
ansi_term = { version = "0.12.1", optional = true }
image = { version = "0.25.5", default-features = false }
