name: Feature Request
description: Suggest an idea for this project.
title: "feat: <title>"
labels: [feature-request]
body:
  - type: textarea
    attributes:
      label: Describe the feature you'd like.
      description: A clear description of what you want to happen in the program.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: A clear description of any alternative solutions you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
