name: "Continous Delivery"

on:
  release:
    types: [published]
env:
  CARGO_TERM_COLOR: always
concurrency: 
  group: 'cd'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo-release Cache
        id: cargo_release_cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-release
          key: ${{ runner.os }}-cargo-release

      - run: cargo install cargo-release
        if: steps.cargo_release_cache.outputs.cache-hit != 'true'

      - name: cargo login
        run: cargo login "$CRATES_IO_API_TOKEN"
        env:
         CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

      # Cargo's check cannot compile `ascii-img-cli`
      #- name: install dependencies
      #  run: sudo apt install pkg-config dav1d -y

      - name: cargo release publish
        run: |-
          cargo release \
            publish \
            --workspace \
            --all-features \
            --allow-branch HEAD \
            --no-verify \
            --no-confirm \
            --execute
