name: "Continous Delivery"

on:
  release:
    types: [published]
env:
  CARGO_TERM_COLOR: always
concurrency: 
  group: 'cd'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo login
        run: cargo login "$CRATES_IO_API_TOKEN"
        env:
         CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: cargo release publish
        continue-on-error: true
        run: |-
          for crate in ascii-img ascii-img-cli; do
            cargo publish --no-verify -p $crate
          done
