name: "Continous Integation"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
concurrency: 
  group: 'ci'
  cancel-in-progress: true

jobs:
  test-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run `cargo check`
      run: cargo check --tests --verbose
    - name: Run `cargo clippy`
      run: cargo clippy
